enum_discrim_align_threshold = 20
format_code_in_doc_comments = true
blank_lines_upper_bound = 2 
force_multiline_blocks = true
hex_literal_case = "Upper"
reorder_imports = true
fn_single_line = true
format_strings = true
comment_width = 80
wrap_comments = true
format_macro_matchers = true
indent_style = "Block"
brace_style = "AlwaysNextLine"
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
format_macro_bodies = true
max_width = 120
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20